name: pl_MessagesEvent
version: '${project.version}'
main: com.takutou.pl_messagesevent.Pl_MessagesEvent
api-version: '1.20'

commands:
  kit:
    description: Your description
    usage: /<command>
    permission: yourplugin.yourcommandpermission