name: pl_MessagesEvent
version: '${project.version}'
main: com.takutou.pl_messagesevent.Pl_MessagesEvent
api-version: '1.20'

commands:
  kit:
    description: Your description
    usage: /<command>
    permission: yourplugin.yourcommandpermission
  setannounce:
    description: Sets the announcement message.
    usage: /setannounce <message>
  setannouncesec:
    description: Sets the announcement interval in seconds.
    usage: /setannounceinterval <seconds>
  getdog:
    description: get dog!.
    usage: /getdog